# fly.toml app configuration file generated for nwber-data-viz on 2024-11-23T16:18:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwber-data-viz'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  cpus = 1
  memory = 1024 #mb
  #kernel_args = "no-hlt=true"

[[restart]]
  policy = "on-failure"
  retries = 3
  processes = ["app"]

[deploy]
  strategy = "canary"

